version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: cmake install
          command: |
            sudo apt remove --purge --auto-remove cmake
            sudo wget -qO- "https://github.com/Kitware/CMake/releases/download/v3.18.3/cmake-3.18.3-Linux-x86_64.tar.gz" 
            sudo tar cmake-3.18.3-Linux-x86_64.tar.gz --strip-components=1 -xz -C /usr/local
      - run:
          name: cmake build
          command: |
            cmake -H. -Bbuild
            cmake --build build
