version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: cmake install
          command: |
            sudo apt remove --purge --auto-remove cmake
            mkdir ~/cmake
            cd ~/cmake
            wget https://github.com/Kitware/CMake/releases/download/v3.18.3/cmake-3.18.3-Linux-x86_64.tar.gz
            tar xf cmake-3.18.3-Linux-x86_64.tar.gz
            export PATH="`pwd`/cmake-3.18.3-Linux-x86_64/bin:$PATH" # save it in .bashrc if needed
            PATH=$HOME/bin:$PATH
            which cmake
      - run:
          name: cmake build
          command: |
            cmake -H. -Bbuild
            cmake --build build
