version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run: mkdir build
      - run: cd build
      - run: 'cmake -H. -Bbuild'
      - run: 'cmake --build build'
