version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          command: cmake -S . -B build
      - run:
          commnd: cmake --build build
