version: 2.1
jobs:
  build:
    executor: exectr
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run: mkdir build; cd build
      - run: 'cmake ..'
      - run: 'make -j$(nproc)'
